// app actions
export const CLOSE_NOTEBOOK = "CLOSE_NOTEBOOK";
export const FETCH_NOTEBOOKS = "FETCH_NOTEBOOKS";
export const SAVE_NOTE = "SAVE_NOTE";
export const SAVE_SPIN_START = "SAVE_SPIN_START";
export const SAVE_SPIN_END = "SAVE_SPIN_END";
export const SET_ACTIVE_NOTE = "SET_ACTIVE_NOTE";
export const SET_CHANGES_SAVED = "SET_CHANGES_SAVED";
export const SET_EDITOR_DIRTY = "SET_EDITOR_DIRTY";
export const SET_MENU_LOADING = "SET_MENU_LOADING";

// auth actions
export const USER_LOADING = "USER_LOADING";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_LOGOUT = "USER_LOGOUT";

// note actions
export const ADD_NEW_NOTE = "ADD_NEW_NOTE";
export const ADD_NEW_NOTEBOOK = "ADD_NEW_NOTEBOOK";
export const DELETE_NOTE = "DELETE_NOTE";
export const DELETE_NOTEBOOK = "DELETE_NOTEBOOK";
export const EVICT_NOTE = "EVICT_NOTE";
export const RENAME_NOTE = "RENAME_NOTE";
export const RENAME_NOTEBOOK = "RENAME_NOTEBOOK";

// settings reducer
export const DELETE_BACKPACK = "DELETE_BACKPACK";
export const SETTINGS_INIT = "SETTINGS_INIT";
export const SETTINGS_SAVE_PERSONAL_DETAILS = "SETTINGS_SAVE_PERSONAL_DETAILS";
export const SET_PERSONAL_DETAILS_LOADING = "SET_PERSONAL_DETAILS_LOADING";
export const SET_APP_SETTINGS_LOADING = "SET_APP_SETTINGS_LOADING";
export const SET_SECURITY_SETTINGS_LOADING = "SET_SECURITY_SETTINGS_LOADING";
export const SETTINGS_CHANGE_LANGUAGE = "SETTINGS_CHANGE_LANGUAGE";
export const SETTINGS_CHANGE_AUTO_SAVE = "SETTINGS_CHANGE_AUTO_SAVE";
export const SETTINGS_CHANGE_CLOSE_ON_CLICK = "SETTINGS_CHANGE_CLOSE_ON_CLICK";
export const UNLINK_SOCIAL_ACCOUNT = "UNLINK_SOCIAL_ACCOUNT";
export const UPDATE_AVATAR = "UPDATE_AVATAR";

// error reducer
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_ERRORS = "GET_ERRORS";
export const SET_CHANGE_PASSWORD_ERRORS = "SET_CHANGE_PASSWORD_ERRORS";

// edit article reducer
export const APPEND_ARTICLE = "APPEND_ARTICLE";
export const DELETE_AND_CLOSE_COLLECTION = "DELETE_AND_CLOSE_COLLECTION";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const EDIT_ARTICLE_RESET = "EDIT_ARTICLE_RESET";
export const INITIALISE_EDIT_COLLECTION = "INITIALISE_EDIT_COLLECTION";
export const POST_ARTICLE_SAVE_UPDATE_COLLECTION = "POST_ARTICLE_SAVE_UPDATE_COLLECTION";
export const SET_ARTICLE_CARD_LOADING = "SET_ARTICLE_CARD_LOADING";
export const SET_BACKPACK_METADATA = "SET_BACKPACK_METADATA";
export const SET_COLLECTION_CARD_LOADING = "SET_COLLECTION_CARD_LOADING";
export const SET_EDIT_ARTICLE = "SET_EDIT_ARTICLE";
export const UPDATE_ACCESS_STATUS = "UPDATE_ACCESS_STATUS";
export const UPDATE_COLLECTION_DETAILS = "UPDATE_COLLECTION_DETAILS";
// search
export const POST_SEARCH = "POST_SEARCH";
export const SEARCH_INCLUDE_COLLECTION = "SEARCH_INCLUDE_COLLECTION";
export const SET_SEARCH_LOADING = "SET_SEARCH_LOADING";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const SET_SEARCH_TAGS = "SET_SEARCH_TAGS";
export const SET_SEARCH_FILTER = "SET_SEARCH_FILTER";

// reading
export const BOOKMARK_ARTICLE = "BOOKMARK_ARTICLE";
export const BOOKMARK_READ_NEXT_ARTICLE = "BOOKMARK_READ_NEXT_ARTICLE";
export const CLEAR_READING_DATA = "CLEAR_READING_DATA";
export const INIT_READING_DATA = "INIT_READING_DATA";
export const SELECT_READING_FOOTER_TAB = "SELECT_READING_FOOTER_TAB";
export const SET_ARTICLE_VOTE = "SET_ARTICLE_VOTE";

// bookmark
export const RESET_BOOKMARKS_CACHE = "RESET_BOOKMARKS_CACHE";
export const SET_BOOKMARKS_LOADING = "SET_BOOKMARKS_LOADING";
export const SET_BOOKMARKS_OPEN = "SET_BOOKMARKS_OPEN";
export const SET_BOOKMARKS_PAGE_CONTENT = "SET_BOOKMARKS_PAGE_CONTENT";
export const SET_BOOKMARKS_ACTIVE_PAGE = "SET_BOOKMARKS_ACTIVE_PAGE";