version: 2.1

orbs:
    docker: circleci/docker@0.5.13
    heroku: circleci/heroku@1.2.6

jobs:
    build:
        docker:
            - image: circleci/python:3.7.2-node
        steps:
            - checkout
            - run:
                name: Install yarn
                command: curl -o- -L https://yarnpkg.com/install.sh | bash
            - restore_cache:
                name: Restore Yarn Package Cache
                keys:
                    - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                name: Install Dependencies
                command: yarn install --immutable
            - save_cache:
                name: Save Yarn Package Cache
                key: yarn-packages-{{ checksum "yarn.lock" }}
                paths:
                    - ~/.cache/yarn
            - run:
                name: Build
                command: CI=false yarn build
    deploy:
        executor: heroku/default
        steps:
            - checkout
            - heroku/install
            - docker/publish:
                image: notex-client
                tag: latest
                context: Heroku
                registry: registry.heroku.com
                docker-username: _
                docker-password: $HEROKU_API_KEY
            - heroku/release-docker-image:
                app-name: notex-client
                process-types: web
workflows:
    build_deploy:
        jobs:
            - docker/publish:
                filters:
                    branches:
                        only:
                            - feature/docker-hosting
                image: notex-client
                tag: latest
                context: Heroku
                registry: registry.heroku.com
                docker-username: _
                docker-password: $HEROKU_API_KEY
            - deploy:
                filters:
                    branches:
                        only:
                            - feature/docker-hosting   
                requires:
                    - docker/publish
            # - build:
            #     filters:
            #         branches:
            #             only:
            #                 - feature/docker-hosting
            # - heroku/push-docker-image:
            #     app-name: notex-client
            #     pre-deploy:
            #         - run:
            #             name: Login to docker service
            #             command: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
            #     filters:
            #         branches:
            #             only:
            #                 - feature/docker-hosting
            #     # requires:
            #     #     - build
            #     context: Heroku