version: 2.1

orbs:
    docker: circleci/docker@0.5.13
    heroku: circleci/heroku@1.2.6

jobs:
    # build:
    #     docker:
    #         - image: circleci/python:3.7.2-node
    #     steps:
    #         - checkout
    #         - run:
    #             name: Install yarn
    #             command: curl -o- -L https://yarnpkg.com/install.sh | bash
    #         - restore_cache:
    #             name: Restore Yarn Package Cache
    #             keys:
    #                 - yarn-packages-{{ checksum "yarn.lock" }}
    #         - run:
    #             name: Install Dependencies
    #             command: yarn install --immutable
    #         - save_cache:
    #             name: Save Yarn Package Cache
    #             key: yarn-packages-{{ checksum "yarn.lock" }}
    #             paths:
    #                 - ~/.cache/yarn
    #         - run:
    #             name: Build
    #             command: CI=false yarn build
    deploy:
        executor: heroku/default
        steps:
            - heroku/install
            - checkout
            - run: docker login -u _ -p $HEROKU_API_KEY registry.heroku.com
            - heroku/push-docker-image:
                app-name: notex-client
                api-key: HEROKU_API_KEY
                process-types: web
            - heroku/release-docker-image:
                app-name: notex-client
                api-key: HEROKU_API_KEY
                process-types: web
    
workflows:
    build_deploy:
        jobs:
            - deploy:
                context: Heroku
                filters:
                    branches:
                        only:
                            - feature/docker-hosting
            # - docker/publish:
            #     context: Heroku
            #     filters:
            #         branches:
            #             only:
            #                 - feature/docker-hosting
            #     image: notex-client
            #     tag: latest
            #     registry: registry.heroku.com
            #     docker-username: _
            #     docker-password: HEROKU_API_KEY
            # - deploy:
            #     context: Heroku
            #     filters:
            #         branches:
            #             only:
            #                 - feature/docker-hosting   
            #     requires:
            #         - docker/publish
            # - build:
            #     filters:
            #         branches:
            #             only:
            #                 - feature/docker-hosting
            # - heroku/push-docker-image:
            #     app-name: notex-client
            #     pre-deploy:
            #         - run:
            #             name: Login to docker service
            #             command: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
            #     filters:
            #         branches:
            #             only:
            #                 - feature/docker-hosting
            #     # requires:
            #     #     - build
            #     context: Heroku